package service

import (
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/gera2ld/caddy-gen/internal/config"
	"github.com/gera2ld/caddy-gen/internal/docker"
	"github.com/gera2ld/caddy-gen/internal/generator"
)

const banner = "# Generated by Caddy-gen at "

// Service is the main service
type Service struct {
	docker    *docker.Client
	generator *generator.Generator
	config    *config.Config
}

// NewService creates a new Service
func NewService() (*Service, error) {
	cfg := config.NewConfig()
	dockerClient, err := docker.NewClient(cfg)
	if err != nil {
		return nil, err
	}
	gen := generator.NewGenerator(dockerClient, cfg)
	return &Service{
		docker:    dockerClient,
		generator: gen,
		config:    cfg,
	}, nil
}

// Close closes the service
func (s *Service) Close() error {
	return s.docker.Close()
}

// Run runs the service
func (s *Service) Run() error {
	s.CheckConfig()
	log.Println("Waiting for Docker events...")
	s.docker.WatchEvents(s.CheckConfig)
	return nil
}

// CheckConfig checks and updates the configuration
func (s *Service) CheckConfig() {
	currentConfig := stripBanner(s.readConfig(s.config.OutFile))
	newConfig, err := s.generator.GenerateConfig()
	if err != nil {
		log.Printf("Failed to generate config: %v", err)
		return
	}
	if currentConfig != newConfig {
		newConfig = generateBanner() + newConfig
		s.writeConfig(s.config.OutFile, newConfig)
		s.notifyConfigChange()
	} else {
		log.Println("No change, skip notifying")
	}
}

func generateBanner() string {
	timestamp := time.Now().Format(time.RFC3339)
	return fmt.Sprintf("%s %s\n\n", banner, timestamp)
}

func stripBanner(config string) string {
	if strings.HasPrefix(config, banner) {
		i := strings.Index(config, "\n\n")
		if i > 0 {
			config = config[i+2:]
		}
	}
	return config
}

// readConfig reads the configuration from the file
func (s *Service) readConfig(filePath string) string {
	data, err := os.ReadFile(filePath)
	if err != nil && !os.IsNotExist(err) {
		log.Printf("Failed to read config file: %v", err)
	}
	return string(data)
}

// writeConfig writes the configuration to the file
func (s *Service) writeConfig(filePath, config string) {
	err := os.WriteFile(filePath, []byte(config), 0644)
	if err != nil {
		log.Printf("Failed to write config: %v", err)
	}
	log.Printf("Caddy config written: %s", filePath)
}

// notifyConfigChange notifies that the configuration has changed
func (s *Service) notifyConfigChange() {
	s.docker.Notify()
}
